version: '3.8'

services:
  backend:
    build: ./backend
    container_name: playeng-backend
    restart: unless-stopped
    expose:
      - "5000"

  frontend:
    build: ./frontend
    container_name: playeng-frontend
    restart: unless-stopped
    ports:
      - "5008:80"
    depends_on:
      - backend
